// react/players_CRUD2/src/App.jsx
/**
 * Copy paste your code from the App.jsx file here from the previous exercise.
 *
 * Use similar logic as in the Vue CRUD2 exercise and add authentication to
 * the app.
 *
 * Backend is still using Basic Auth, so you must use the same logic as in the
 * Vue exercise and include the Authorization header to requests to backend.
 *
 * REMEMBER: use the same ids, classes and attributes as in the Vue exercise in
 * the same places to pass the tests. Remember to pass in the appropriate props
 * to the child components.
 *
 * BEWARE: The component props may be different from the Vue exercise and the
 * tests will not pass if you use the wrong props.
 *
 * @format
 */

// --------- IMPORTS ---------
import React, { useState } from 'react';

// --------- COMPONENT IMPORTS ---------
import { ListPlayers } from './components/ListPlayers.jsx';
import { AddPlayer } from './components/AddPlayer.jsx';
import { SelectedPlayer } from './components/SelectedPlayer.jsx';
import { RequestStatus } from './components/RequestStatus.jsx';
import { AuthUser } from './components/AuthUser.jsx';

// --------- CONST VALUES ---------
const REQ_STATUS = {
	loading: 'Loading...',
	success: 'Finished!',
	error: 'An error has occurred!!!',
};
const URL = "http://localhost:3001/api/players/";


//const context = React.createContext('testingc');

function App() {
	// --------- STATE ---------
	const [reqStatus, setReqStatus] = useState(REQ_STATUS.loading);
	const [players, setPlayers] = useState([]);
	const [selectedPlayer, setSelectedPlayer] = useState("");
	const [username, setUsername] = useState("");
	const [password, setPassword] = useState("");
	const [isLoggedIn, setIsLoggedIn] = useState("");

	// --------- FUNCTIONS ---------
	//useEffect(() => { fetchPlayers() }, []);
	function fetchPlayers() {
		setReqStatus(REQ_STATUS.loading);
		let credentials = window.btoa('admin' + ':' + 'secret');
		const requestOptions = {
			method: "GET",
			headers: {
				"Content-Type": "application/json",
				"Authorization": "Basic " + credentials
			}
		};
		fetch(URL, requestOptions)
		.then(response => response.json())
		.then(data => setPlayers(data))
		.then(() => { 
			setReqStatus(REQ_STATUS.success); 
		})

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function fetchPlayer(playerId) {
		setReqStatus(REQ_STATUS.loading);
		let credentials = window.btoa('admin' + ':' + 'secret');
		const requestOptions = {
			method: "GET",
			headers: {
				"Content-Type": "application/json",
				"Authorization": "Basic " + credentials
			}
		};
		fetch(URL + playerId, requestOptions)
		.then(response => response.json())
		.then(data => setSelectedPlayer(data))
		.then(() => { setReqStatus(REQ_STATUS.success); })

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function addPlayer(name) {
		setReqStatus(REQ_STATUS.loading);
		let credentials = window.btoa('admin' + ':' + 'secret');
		const requestOptions = {
			method: 'POST',
          	headers: { 
				'Content-Type': 'application/json',
				"Authorization": "Basic " + credentials
			},
			body: JSON.stringify({ name: name, isActive: true })
		};
		fetch(URL, requestOptions)
		.then(response => response.json())
		.then(data => setPlayers(oldPlayers => [...oldPlayers, data]))
		.then(() => { setReqStatus(REQ_STATUS.success); })

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function deletePlayer(playerId) {
		setReqStatus(REQ_STATUS.loading);
		let credentials = window.btoa('admin' + ':' + 'secret');
		const requestOptions = {
			method: "DELETE",
			headers: {
				"Content-Type": "application/json",
				"Authorization": "Basic " + credentials
			}
		};
		fetch(URL + playerId, requestOptions)
		.then(() => setPlayers(oldPlayers =>
			oldPlayers.filter(player => player.id !== playerId)))
		.then(() => { 
			setSelectedPlayer("");
			setReqStatus(REQ_STATUS.success); 
		})

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function updatePlayer(playerData) {
		setReqStatus(REQ_STATUS.loading);
		let credentials = window.btoa('admin' + ':' + 'secret');
		const requestOptions = {
			method: 'PUT',
          	headers: { 
				'Content-Type': 'application/json',
				"Authorization": "Basic " + credentials
			},
			body: JSON.stringify({ isActive: !playerData.isActive })
		};
		fetch(URL + playerData.id, requestOptions)
		.then(response => response.json())
		.then(data => {
			setSelectedPlayer(data);
			// finds players index in list and updates the player using that index
			let index = players.findIndex(pl => pl.id === data.id);
			setPlayers(oldPlayers => {
				return [...oldPlayers.slice(0, index), data, ...oldPlayers.slice(index + 1)]
			});
		})
		.then(() => { setReqStatus(REQ_STATUS.success); })

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function registerUser(name, password) {
		setReqStatus(REQ_STATUS.loading);
		const requestOptions = {
			method: "POST",
			headers: {"Content-Type": "application/json"},
			body: JSON.stringify({
				username: name,
				password: password
			})
		};
		fetch("http://localhost:3001/api/users", requestOptions)
		.then((response) => {
			if (response.status == 201) {
				setUsername(name);
				setPassword(password);
				setIsLoggedIn(true);
				fetchPlayers();
				setReqStatus(REQ_STATUS.success);
			} else { setReqStatus(REQ_STATUS.error); }
		})
		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function loginUser(name, password) {
		setReqStatus(REQ_STATUS.loading);
		let credentials = window.btoa('admin' + ':' + 'secret');
		const requestOptions = {
			method: "GET",
			headers: {
				"Content-Type": "application/json",
				"Authorization": "Basic " + credentials
			}
		};
		fetch(URL, requestOptions)
		.then((response) => {
			setPlayers(response.json());
			setUsername(name);
			setPassword(password);
			setIsLoggedIn(true);
			setReqStatus(REQ_STATUS.success);
		})
		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function logout() {
		console.log("logout");
		setReqStatus(REQ_STATUS.loading);
		setPlayers([]);
		setSelectedPlayer("");
		setUsername("");
		setPassword("");
		setIsLoggedIn("");
	};

	function regOrLogIn(register, name, password) {
		register ? loginUser(name, password) : registerUser(name, password)
	};
	
	return (
		<>
			<AuthUser handleSubmit={regOrLogIn} isLoggedIn={isLoggedIn} handleLogout={logout}/>
			<RequestStatus status={reqStatus} />
			<AddPlayer handleSubmit={addPlayer}/>
			<ListPlayers players={players} selectPlayer={fetchPlayer}/>
			<SelectedPlayer handleDelete={deletePlayer} handleUpdate={updatePlayer} player={selectedPlayer}/>
		</>
	);
}

export default App;

// vue/players_CRUD2/src/App.vue
<!-- 
  COPY AND PASTE THE CODE FROM THE PREVIOUS EXERCISE, BUT:
  - Beware, the template is different: AuthUser is now a child of the root div element. When copy-pasting the logic to
  the new template, make sure to add the AuthUser component back in. 
  - You are no longer automatically fetching the players every time the App is rendered. Instead, you should only
  fetch the players when the user is logged in successfully.

  What is the function of the AuthUser component in the big picture?
  - Depending on the state of the AuthUser component, the other components should be displayed or hidden
  (except for the RequestStatus component, which is always visible). If the user is logged in, the AddPlayer, ListPlayers,
  and SelectedPlayer components should be displayed. If the user is not logged in, only the AuthUser component and the
  RequestStatus component should be displayed.

  1. Inside the root div element, give the AuthUser the appropriate props and event listeners. It should emit the
  "login", "register", and "logout" events. You need to give it the "isLoggedIn" prop, which is used to determine the
  state of the AuthUser component. If you removed the AuthUser componenet because you overwrote the whole template with
  the new one, remember to add it back in.
---------------------
  2. Create a method for registering a user when the AuthUser component emits the "register" event. This method should
  handle the logic for registering a user. After a successful registration, save the user's username and password into
  the App's state. 
 
  The backend uses the HTTP Basic auth, which means that the username and password as sent in base64 encoded format in
  the Authorization header upon every request except for the registration request. 

  The header contents should be of the following format: "Basic <base64 encoded username:password>". The username and
    password should be separated by a colon. The username and password should be base64 encoded. You can use the btoa()
    function to encode the username and password. For example, if the username is "user" and the password is "password",
    the header could be generated with the following code: `Basic ${window.btoa(`user:password`)}`; 

  The backend will respond with 401 if the Authorization header is missing, and with a status of 403 if the credentials
  are invalid. 
--------------------------
  After a succesful registration, the app should attempt to fetch players from the database. If it fails to fetch the
  players, then the user should stay logged out. If it succeeds, the user should be logged in and the app state should
  be updated accordingly and the players list should be displayed. Notice that separate login is not required after a
  successful registration, because the user is already logged in.
  
  3. Create a method for logging in when the AuthUser component emits the "login" event. This method should handle the
  logic for logging in a user. As described earlier, the backend does not have a separate login endpoint. Instead, the
  app should try to fetch players from the database with the given credentials using Basic auth. If the request is
  successful, the user is logged in and the app state should be updated accordingly.

  4. Create a method for logging out when the AuthUser component emits the "logout" event. This method should handle
  the logic for logging out a user. This method should be called when the logout event is emitted from the AuthUser
  component. When the user logs out, the application should be reset to its initial state (ergo, remove all data that
  was fetched from the database)

  HINT: Remember to add the Authorization header to every request except the user registration. 

 -->

 <template>
  <div>
    <AuthUser v-bind:isLoggedIn="isLoggedIn" @login="login" @register="register" @logout="logout" v-if="!isLoggedIn"/>
    <RequestStatus v-bind:reqStatus="reqStatus"/>
    <AddPlayer @add-player="addPlayer" v-if="isLoggedIn"/>
    <ListPlayers v-bind:players="players" v-bind:getPlayer="getPlayer" v-if="isLoggedIn"/>
    <SelectedPlayer v-bind:player="player" @delete-player="deletePlayer" @put-player="updatePlayer" v-if="isLoggedIn"/>
  </div>
</template>

<script>
import AddPlayer from './components/AddPlayer.vue';
import ListPlayers from './components/ListPlayers.vue';
import SelectedPlayer from './components/SelectedPlayer.vue';
import RequestStatus from './components/RequestStatus.vue';
import AuthUser from './components/AuthUser.vue';

const REQ_STATUS = {
  loading: 'Loading...',
  success: 'Finished!',
  error: 'An error has occurred!!!'
};

const URL = 'http://localhost:3001'

export default {
  data() {
    return {
      players: [],
      player: "",
      reqStatus: "",
      isLoggedIn: false,
      username: "",
      password: ""
    }
  },
  created() {
    this.register("admin2", "secret2");
    //this.fetchPlayers();
  },
  methods: {
    async fetchPlayers() {
      this.reqStatus = REQ_STATUS["loading"]
      let credentials = this.username + ':' + this.password;
      try {
        const requestOptions = {
          method: "GET",
          headers: { 
            "Content-Type": "application/json",
            "Authorization": `Basic ${window.btoa(credentials)}`
          }
        };
        const response = await fetch(URL + '/api/players/', requestOptions);
        const data = await response.json();
        this.players = data;
        this.reqStatus = REQ_STATUS["success"];
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"];
      }
    },
    async getPlayer(playerId) {
      this.reqStatus = REQ_STATUS["loading"];
      let credentials = this.username + ':' + this.password;     
      try {
        const requestOptions = {
          method: "GET",
          headers: { 
            "Content-Type": "application/json",
            "Authorization": `Basic ${window.btoa(credentials)}`
          }
        };
        const response = await fetch(URL + '/api/players/' + playerId, requestOptions);
        const data = await response.json();
        this.player = data;
        this.reqStatus = REQ_STATUS["success"];
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"];
      }
    },
    async addPlayer(name) {
      this.reqStatus = REQ_STATUS["loading"];
      let credentials = this.username + ':' + this.password;
      try {
        const requestOptions = {
          method: "POST",
          headers: { 
            "Content-Type": "application/json",
            "Authorization": `Basic ${window.btoa(credentials)}`
          },
          body: JSON.stringify({
            name: name,
            isActive: true
          })
        }
        const response = await fetch(URL + '/api/players', requestOptions);
        if (response.status == 201) {
          const data = await response.json();
          this.players.push(data);
          this.reqStatus = REQ_STATUS["success"];
        } else {
          this.reqStatus = REQ_STATUS["error"];
        }
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"];
      }
    },
    async deletePlayer(playerId) {
      this.reqStatus = REQ_STATUS["loading"];
      let credentials = this.username + ':' + this.password;
      try {
        const requestOptions = {
          method: "DELETE",
          headers: {
            "Authorization": `Basic ${window.btoa(credentials)}`
          }
        };
        const response = await fetch(URL + '/api/players/' + playerId, requestOptions);
        if (response.status == 200 || response.status == 204) {
          // Remove deleted player from local player list if deleting in db was successful
          this.players = this.players.filter(player => player.id != playerId);
          this.reqStatus = REQ_STATUS["success"];
        } else {
          this.reqStatus = REQ_STATUS["error"];
        }
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"];
      }
    },
    async updatePlayer(playerData){
      this.reqStatus = REQ_STATUS["loading"];
      let credentials = this.username + ':' + this.password;
      try {
        const requestOptions = {
          method: "PUT",
          headers: { 
            "Content-Type": "application/json",
            "Authorization": `Basic ${window.btoa(`admin:secret`)}`
          },
          body: JSON.stringify({
            isActive: !playerData.isActive
          })
        }
        const response = await fetch(URL + '/api/players/' + playerData.id, requestOptions);
        if (response.status == 200) {
          const data = await response.json();
          // Update player data
          index = this.players.findIndex((pl => pl.id == data.id));
          this.players[index] = data;
          this.player = data;
          this.reqStatus = REQ_STATUS["success"];
        } else if (response.status == 204) {
          this.reqStatus = REQ_STATUS["loading"];
        } else {
          this.reqStatus = REQ_STATUS["error"];
        }
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"];
      }
    },
    async register(username, password) {
      this.reqStatus = REQ_STATUS["loading"];
      try {
        const requestOptions = {
          method: "POST",
          headers: { "Content-Type": "application/json"},
          body: JSON.stringify({
            username: username,
            password: password
          })
        };
        const response = await fetch(URL + '/api/users', requestOptions);
        if (response.status == 201) {
          const data = await response.json();
          this.username = data.username;
          this.password = password;
          // if registration success, fetch players and update state
          this.fetchPlayers();
          this.isLoggedIn = true;

          this.reqStatus = REQ_STATUS["success"];
        } else {
          this.reqStatus = REQ_STATUS["error"];
        }
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"];
      }
    }
  },
  components: {
    AuthUser,
    AddPlayer,
    ListPlayers,
    SelectedPlayer,
    RequestStatus
  },
};
</script>
