// vue/players_CRUD/src/App.vue
<!-- 
  COPY AND PASTE YOUR CODE FROM THE PREVIOUS EXERCISE HERE. Also implement the following:

  1. Create a method for adding a new player. This method should handle the logic for adding a new player to the backend
  and updating the players list. This method should also reset the form only if the request was successful.
  This method should be called when the add player form is submitted.

  2. Create a method for deleting a player. This method should handle the logic for deleting a player from the backend and
  updating the players list. This method should be called when the delete button is clicked in the SelectedPlayer component.

  3. Create a method for updating a player. This method should handle the logic for updating a player in the backend and
  updating the players list. This method should be called when the update button is clicked in the SelectedPlayer component.
 -->


<template>
  <div>
    <RequestStatus v-bind:reqStatus="reqStatus"/>
    <AddPlayer @add-player="addPlayer"/>
    <ListPlayers v-bind:players="players" v-bind:getPlayer="getPlayer"/>
    <SelectedPlayer v-bind:player="player" @delete-player="deletePlayer" @put-player="updatePlayer"/>
  </div>
</template>

<script>
import AddPlayer from './components/AddPlayer.vue';
import ListPlayers from './components/ListPlayers.vue';
import SelectedPlayer from './components/SelectedPlayer.vue';
import RequestStatus from './components/RequestStatus.vue';

const REQ_STATUS = {
  loading: 'Loading...',
  success: 'Finished!',
  error: 'An error has occurred!!!'
};

const URL = 'http://localhost:3001'

export default {
  data() {
    return {
      players: [],
      player: "",
      reqStatus: ""
    }
  },
  created() {
    this.fetchPlayers()
  },
  methods: {
    async fetchPlayers() {
      this.reqStatus = REQ_STATUS["loading"]
      try {
        const response = await fetch(URL + '/api/players/')
        const data = await response.json()
        this.players = data
        this.reqStatus = REQ_STATUS["success"]
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"]
      }
    },
    async getPlayer(playerId) {
      this.reqStatus = REQ_STATUS["loading"]     
      try {
        const response = await fetch(URL + '/api/players/' + playerId)
        const data = await response.json()
        this.player = data
        this.reqStatus = REQ_STATUS["success"]
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"]
      }
    },
    async addPlayer(name) {
      this.reqStatus = REQ_STATUS["loading"];
      try {
        const requestOptions = {
          method: "POST",
          headers: { "Content-Type": "application/json"},
          body: JSON.stringify({
            name: name,
            isActive: true
          })
        }
        const response = await fetch(URL + '/api/players', requestOptions);
        if (response.status == 201) {
          const data = await response.json();
          this.players.push(data);
          this.reqStatus = REQ_STATUS["success"];
        } else {
          this.reqStatus = REQ_STATUS["error"];
        }
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"];
      }
    },
    async deletePlayer(playerId) {
      this.reqStatus = REQ_STATUS["loading"];
      try {
        const requestOptions = {
          method: "DELETE"
        };
        const response = await fetch(URL + '/api/players/' + playerId, requestOptions);
        if (response.status == 200 || response.status == 204) {
          // Remove deleted player from local player list if deleting in db was successful
          this.players = this.players.filter(player => player.id != playerId);
          this.reqStatus = REQ_STATUS["success"];
        } else {
          this.reqStatus = REQ_STATUS["error"];
        }
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"];
      }
    },
    async updatePlayer(playerData){
      this.reqStatus = REQ_STATUS["loading"];
      try {
        const requestOptions = {
          method: "PUT",
          headers: { "Content-Type": "application/json"},
          body: JSON.stringify({
            isActive: !playerData.isActive
          })
        }
        const response = await fetch(URL + '/api/players/' + playerData.id, requestOptions);
        if (response.status == 200) {
          const data = await response.json();
          // Update player data
          index = this.players.findIndex((pl => pl.id == data.id));
          this.players[index] = data;
          this.player = data;
          this.reqStatus = REQ_STATUS["success"];
        } else if (response.status == 204) {
          this.reqStatus = REQ_STATUS["loading"];
        } else {
          this.reqStatus = REQ_STATUS["error"];
        }
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"];
      }
    }
  },
  components: {
    AddPlayer,
    ListPlayers,
    SelectedPlayer,
    RequestStatus
  },
};
</script>

// react/players_CRUD/src/App.jsx
/**
 * Copy paste your code from the App.jsx file here from the previous exercise.
 *
 * Use similar logic as in the Vue CRUD exercise to create a new player in the
 * backend when the user submits the form in the AddPlayer component.
 *
 * Likewise, add logic to update the player in the backend when the user clicks
 * the update button in the SelectedPlayer component.
 *
 * Finally, add logic to delete the player in the backend when the user clicks
 * the delete button in the SelectedPlayer component.
 *
 * HINT: Before the above logic, it may be better to start by updating the SelectedPlayer component to use the new props.
 *
 * REMEMBER: use the same ids, classes and attributes as in the Vue exercise in
 * the same places to pass the tests. Remember to pass in the appropriate props
 * to the child components.
 *
 * BEWARE: The component props may be different from the Vue exercise and the
 * tests will not pass if you use the wrong props.
 *
 * @format
 */

// --------- IMPORTS ---------
import React, { useState, useEffect } from 'react';

// --------- COMPONENT IMPORTS ---------
import { ListPlayers } from './components/ListPlayers.jsx';
import { AddPlayer } from './components/AddPlayer.jsx';
import { SelectedPlayer } from './components/SelectedPlayer.jsx';
import { RequestStatus } from './components/RequestStatus.jsx';

// --------- CONST VALUES ---------
const REQ_STATUS = {
	loading: 'Loading...',
	success: 'Finished!',
	error: 'An error has occurred!!!',
};
const URL = "http://localhost:3001/api/players/";


//const context = React.createContext('testingc');

function App() {
	// --------- STATE ---------
	const [reqStatus, setReqStatus] = useState(REQ_STATUS.loading);
	const [players, setPlayers] = useState([]);
	const [selectedPlayer, setSelectedPlayer] = useState("");

	// --------- FUNCTIONS ---------
	useEffect(() => { fetchPlayers() }, []);

	function fetchPlayers() {
		setReqStatus(REQ_STATUS.loading);
		fetch(URL)
		.then(response => response.json())
		.then(data => setPlayers(data))
		.then(() => { setReqStatus(REQ_STATUS.success); })

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function fetchPlayer(playerId) {
		setReqStatus(REQ_STATUS.loading);
		fetch(URL + playerId)
		.then(response => response.json())
		.then(data => setSelectedPlayer(data))
		.then(() => { setReqStatus(REQ_STATUS.success); })

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function addPlayer(name) {
		setReqStatus(REQ_STATUS.loading);
		const requestOptions = {
			method: 'POST',
          	headers: { 'Content-Type': 'application/json'},
			body: JSON.stringify({ name: name, isActive: true })
		};
		fetch(URL, requestOptions)
		.then(response => response.json())
		.then(data => setPlayers(oldPlayers => [...oldPlayers, data]))
		.then(() => { setReqStatus(REQ_STATUS.success); })

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function deletePlayer(playerId) {
		setReqStatus(REQ_STATUS.loading);
		const requestOptions = { method: 'DELETE' };
		fetch(URL + playerId, requestOptions)
		.then(() => setPlayers(oldPlayers =>
			oldPlayers.filter(player => player.id !== playerId)))
		.then(() => { 
			setSelectedPlayer("");
			setReqStatus(REQ_STATUS.success); 
		})

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	function updatePlayer(playerData) {
		setReqStatus(REQ_STATUS.loading);
		const requestOptions = {
			method: 'PUT',
          	headers: { 'Content-Type': 'application/json'},
			body: JSON.stringify({ isActive: !playerData.isActive })
		};
		fetch(URL + playerData.id, requestOptions)
		.then(response => response.json())
		.then(data => {
			setSelectedPlayer(data);
			// finds players index in list and updates the player using that index
			let index = players.findIndex(pl => pl.id === data.id);
			setPlayers(oldPlayers => {
				return [...oldPlayers.slice(0, index), data, ...oldPlayers.slice(index + 1)]
			});
		})
		.then(() => { setReqStatus(REQ_STATUS.success); })

		.catch((error) => {
			console.log(error);
			setReqStatus(REQ_STATUS.error);
		});
	};

	return (
		<>
			<RequestStatus status={reqStatus} />
			<AddPlayer handleSubmit={addPlayer}/>
			<ListPlayers players={players} selectPlayer={fetchPlayer}/>
			<SelectedPlayer handleDelete={deletePlayer} handleUpdate={updatePlayer} player={selectedPlayer}/>
		</>
	);
}

export default App;
