// redux/redux_thunk/src/components/RequestStatus.jsx
/** @format
 * Copy paste your code from the RequestStatus.jsx file here from the previous exercise
 *
 * BEWARE: No props are passed to this component from now on. Instead, all the data is fetched and updated in the redux store.
 */
import { useSelector } from "react-redux";

export const RequestStatus = () => {
  const status = useSelector((state) => state.status);
	return (
		<div>
			<h3>Request status</h3>
			<div id="request-status">{ status }</div>
		</div>
	);
};

// vue/players_CRUD/src/components/RequestStatus.vue
<!-- 
  Copy paste your code from the RequestStatus.vue file here from the previous exercise
 -->


 <template>
  <div>
    <h3>Request status</h3>
    <div id="request-status"> {{reqStatus}} </div>
  </div>
</template>

<script>
export default {
  props: ['reqStatus']
};
</script>

<style scoped>
#request-status {
  content: " ";
  margin: var(--main-margin);
  padding: 20px;
  /* height: 40px; */
  background-color: var(--color-background-soft);
  border: 2px solid var(--color-background-mute);
}
</style>
