// vue/players_fetch/src/App.vue
<!-- 
  1. Inside the root div element, remember to pass in the appropriate props to the child components.

  2. Create two methods for fetching all players and fetching one specific player. The first method should handle
  the logic for fetching all the players and displaying them in the players list. The second method should handle the logic
  for fetching a specific player when that player is clicked in the list. It takes the id of the player as an argument. 

  3. When the component is created, fetch players data and handle it appropriately (store and display).

  Hint: Use the provided REQ_STATUS object to update the request status when necessary. "loading" for when the request
  is in progress, "success" for when the request is successful, and "error" for when the request has failed.
 -->

 <template>
  <div>
    <RequestStatus v-bind:reqStatus="reqStatus"/>
    <ListPlayers v-bind:players="players" @getPlayerEvent="fetchPlayer"/>
    <SelectedPlayer v-bind:player="player"/>
  </div>
</template>

<script>
import ListPlayers from './components/ListPlayers.vue';
import RequestStatus from './components/RequestStatus.vue';
import SelectedPlayer from './components/SelectedPlayer.vue';
// Import assets

const REQ_STATUS = {
  loading: 'Loading...',
  success: 'Finished!',
  error: 'An error has occurred!!!'
};

export default {
  data() {
    return {
      players: [],
      player: "",
      reqStatus: ""
    }
  },
  created() {
    this.reqStatus = REQ_STATUS["loading"]
    this.fetchPlayers()
  },
  methods: {
    async fetchPlayers() {
      try {
        await fetch('http://localhost:3001/api/players/')
                .then(response => response.json())
                .then(json => { this.players = json })
                .then(this.reqStatus = REQ_STATUS["success"])
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"]
      }
    },
    async fetchPlayer(playerId) {     
      try {
        await fetch('http://localhost:3001/api/players/' + playerId)
                .then(response => response.json())
                .then(json => { this.player = json })
                .then(this.reqStatus = REQ_STATUS["success"])
      } catch (error) {
        this.reqStatus = REQ_STATUS["error"]
      }
    }
  },
  components: {
    ListPlayers,
    SelectedPlayer,
    RequestStatus
  },
};
</script>

// redux/react_redux/src/App.jsx
/** @format 
 * 
 * Student instructions:
 * Copy paste the App.jsx file from the previous exercises into this file. In this exercise, you will be introducing redux, which is a state 
 * management library that allows you to manage the state of your application in a single store. The store is a single source of truth for the state 
 * of your application, and it is the only place where the state can be updated. 
 * 
 * The fetch functions will start using action creators from now on. Each action creator will be responsible for updating the redux store with the data 
 * from the request. You can find the template files for the action creators in the src/redux/actionCreators folder. It is your job to implement them, 
 * as well as the reducers that will be used to update the store. The reducers can be found in the src/redux/reducers folder.
 * 
  Hint: Use the provided REQ_STATUS object to update the request status when necessary. "loading" for when the request is in progress, "success" for 
  when the request is successful, and "error" for when the request has failed. The REQ_STATUS object is imported from the src/redux/constants.js file.

*/

// --------- IMPORTS ---------
import React, { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { REQ_STATUS } from './redux/constants.js';
//import { setStatus, setPlayers, setSelectedPlayer, clearSelectedPlayer } from './redux/actionCreators'
import { setStatus } from './redux/actionCreators/statusActions';
import { setPlayers } from './redux/actionCreators/playersActions';
import { setSelectedPlayer, clearSelectedPlayer } from './redux/actionCreators/selectedPlayerActions';

// --------- COMPONENT IMPORTS ---------
import { ListPlayers } from './components/ListPlayers.jsx';
import { SelectedPlayer } from './components/SelectedPlayer.jsx';
import { RequestStatus } from './components/RequestStatus.jsx';

const URL = "http://localhost:3001/api/players/";

function App() {
  const dispatch = useDispatch();

	// --------- FUNCTIONS ---------
	useEffect(() => { fetchPlayers() }, []);

	function fetchPlayers() {
		dispatch(setStatus(REQ_STATUS.loading));
		fetch(URL)
		.then(response => response.json())
		.then(data => dispatch(setPlayers(data)))
		.then(() => { dispatch(setStatus(REQ_STATUS.success)); })

		.catch((error) => {
			console.log(error);
      dispatch(setStatus(REQ_STATUS.error));
		});
	};

	function fetchPlayer(playerId) {
		dispatch(setStatus(REQ_STATUS.loading));
		fetch(URL + playerId)
		.then(response => response.json())
		.then(data => dispatch(setSelectedPlayer(data)))
		.then(() => { dispatch(setStatus(REQ_STATUS.success)); })

		.catch((error) => {
			console.log(error);
			dispatch(setStatus(REQ_STATUS.error));
		});
	};

	return (
		<>
			<RequestStatus />
			<ListPlayers selectPlayer={fetchPlayer}/>
			<SelectedPlayer />
		</>
	);
}

export default App;
